In [1]:
from Helper.Load.load import Base_Load
from Helper.Load.supervised import Supervised
from Helper.Load.regression import Regression
from Helper.Load.classification import Classification
from Helper.Visual.Visual import Visual
from Helper.Visual.classification import VClassification
from Helper.Transform.Transform.classification import Classificaton_Transform
from Helper.Train.Train import Train

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
loadC = Classification("Data", "wisconsin.dat", "wisconsin-names.txt")

In [3]:
transformC = Classificaton_Transform(loadC)

> /Users/jacob/Desktop/Project/MachineLearning/KEEL/Projects/Supervised/Standard/wisconsin/Helper/Transform/Transform/classification.py(32)visual_data()
-> return pd.DataFrame(self.featureU().transform(data), columns=data.columns)

(Pdb)  c

In [6]:
transformC.data

,ClumpThickness,CellSize,CellShape,MarginalAdhesion,EpithelialSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,2,2,2,1,1,1,7,1,1,2
1,4,1,2,1,2,1,3,1,1,2
2,5,4,3,1,2,<null>,2,3,1,2
3,9,5,5,2,2,2,5,1,1,4
4,2,1,1,1,2,1,3,1,1,2
5,2,1,1,1,2,1,2,1,1,2
6,1,1,1,1,2,1,1,1,8,2
7,5,4,5,1,8,1,3,6,1,2
8,3,1,1,1,2,1,2,1,1,2
9,6,5,5,8,4,10,3,4,1,4
10,2,7,10,10,7,10,4,9,4,4
11,5,1,1,1,2,1,3,1,1,2
12,1,1,1,1,2,1,2,1,1,2
13,8,10,10,10,6,10,10,10,10,4
14,1,1,1,1,2,1,3,1,1,2
15,1,1,1,1,2,1,2,1,2,2
16,3,1,1,1,2,2,3,1,1,2
17,4,1,1,1,2,1,1,1,1,2
18,4,1,1,1,2,1,1,1,1,2
19,5,1,1,1,2,1,2,1,1,2
20,5,1,1,1,2,1,3,1,1,2
21,1,1,1,1,2,5,1,1,1,2
22,5,3,3,2,3,1,3,1,1,2
23,4,1,1,1,2,1,2,1,1,2
24,8,2,4,1,5,1,5,4,4,4
25,1,1,1,1,1,1,3,1,1,2
26,4,1,1,1,2,2,3,2,1,2
27,4,1,1,3,2,1,3,1,1,2
28,3,1,1,2,2,1,1,1,1,2
29,3,1,2,2,2,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...
438,5,3,4,3,4,5,4,7,1,2
439,6,1,1,1,1,1,1,1,1,2
440,1,1,1,1,2,2,2,1,1,2
441,8,3,8,3,4,9,8,9,8,4
442,1,1,1,1,2,1,2,1,1,2
443,5,2,2,4,2,4,1,1,1,2
444,5,1,1,1,2,1,2,1,1,2
445,1,1,1,1,2,1,2,1,1,2
446,5,5,5,8,10,8,7,3,7,4
447,1,1,1,1,2,1,1,1,1,2
448,1,1,1,1,2,1,1,1,1,2
449,5,1,2,10,4,5,2,1,1,2
450,10,10,7,8,7,1,10,10,3,4
451,3,3,5,2,3,10,7,1,1,4
452,4,1,1,1,2,1,1,1,1,2
453,3,1,1,1,2,1,3,1,1,2
454,5,1,2,1,2,1,2,1,1,2
455,10,8,10,1,3,10,5,1,1,4
456,1,3,1,2,2,2,5,3,2,2
457,2,1,1,1,2,1,1,1,1,2
458,5,1,1,6,3,1,2,1,1,2
459,3,2,1,1,2,1,2,2,1,2
460,5,2,2,2,3,1,1,3,1,2
461,3,1,1,1,2,1,1,1,1,2
462,3,6,6,6,5,10,6,8,3,4
463,5,7,7,1,5,8,3,4,1,2
464,5,5,5,6,3,10,3,1,1,4
465,3,1,1,1,2,1,2,1,1,2
466,4,1,1,1,2,1,2,1,1,2
467,10,6,4,3,10,10,9,10,1,4